before:
  hooks:
    - go mod tidy -compat=1.17
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    wrap_in_directory: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
brews:
  -
    name: jclockedio
    tap:
      owner: masa0221
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    folder: Formula
    homepage: "https://github.com/masa0221/jclockedio"
    description: "This is a things for clocked in/out to Jobcan, then it results are send to Chatwork."
    license: "MIT"
    custom_block: |
      depends_on cask: "chromedriver"

